export default {
    ON_AUTH_STATE_CHANGED: 'ON_AUTH_STATE_CHANGED',
    ON_USER_STATUS_CHANGED: 'ON_USER_STATUS_CHANGED',
    FETCH_ALL_BOOKDATA: 'FETCH_ALL_BOOKDATA',
    SEND_ITEM_BOOK_REQUEST: 'SEND_BOOK_LIST_REQUEST',
}
